### ISSUE TITLE
Cannot Generate Repository From Template Due to File Size

### ISSUE THREAD

**Issue by ascriptmaster** [Gremious/StS-DefaultModBase#56]
Because there are two files in the repository over 10MB in size, GitHub refuses to create repositories based on this template.

The files in question are:

* theDefault/src/main/resources/theDefaultResources/images/charSelect/PortraitBG.psd (10.4 MB)
* theDefault/src/main/resources/theDefaultResources/images/events/Events.psd (15.9 MB)

Obviously we can still create mods by downloading the source directly, but if these file sizes were reduced somehow that would be cool

**Comment by Gremious** [comment]
9091a48..2603650 should hopefully fix it

**Comment by hundun000** [comment]
The master-branch is ok. But enable "Include all branches" while generating templent still has this problem.
It seems other branches is helpful for clone. Will the fix be used in all branches?
