### ISSUE TITLE
Add groupId to modid (ModInfo)

### ISSUE THREAD

**Issue by GniLudio** [Gremious/StS-DefaultModBase#64]
To avoid duplicate mod ids, it would be good to include the groupId in it.
`"modid": "${project.groupId}:${project.artifactId}",`

Old version:
`"modid": "${project.artifactId}",`

**Comment by Gremious** [comment]
99% of the time the group id is just the artifact id in lowercase, so this won't actually stop any conflicts.
I'll consider putting the creator name in the there by default or something though
